# .github/workflows/deploy.yml
name: Déploiement auto sur push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement distant
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Connexion SSH et redémarrage de l'app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /chemin/vers/ton/app
          git pull origin main
          docker compose down
          docker compose up -d --build
