name: 🚀 Test Local Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Installer Docker Compose (si besoin)
        run: |
          docker --version
          docker-compose --version

      - name: 🐳 Redémarrer l'app avec Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build
