name: 🚀 Build + Deploy via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 🧠 Important : on utilise TON runner local

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v3

    - name: 🐳 Build de l'image Docker
      run: docker build -t tpm-app .

    - name: 🔍 Test injection des secrets (version Windows PowerShell)
      shell: powershell
      run: |
        Set-Content -Path username.txt -Value "${{ secrets.DOCKER_USERNAME }}"
        Set-Content -Path password.txt -Value "${{ secrets.DOCKER_PASSWORD }}"
        $usernameLength = (Get-Content username.txt).Length
        $passwordLength = (Get-Content password.txt).Length
        Write-Host "Username length: $usernameLength"
        Write-Host "Password length: $passwordLength"
    

    - name: 🔐 Connexion Docker (version Windows)
      shell: powershell
      run: |
        $pass = "${{ secrets.DOCKER_PASSWORD }}"
        echo $pass | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: 🏷️ Tag de l'image
      run: docker tag tpm-app docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest

    - name: 📤 Push de l'image
      run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest

    - name: 🐳 Déploiement local (pull + run)
      run: |
        echo "🔄 Pull de l'image depuis Docker Hub"
        docker pull mathieuawels/tpm-app:latest

        echo "🛑 Suppression de l'ancien conteneur"
        docker stop tpm-app-container || true
        docker rm tpm-app-container || true

        echo "🚀 Lancement du conteneur"
        docker run -d --name tpm-app-container -p 8080:5000 mathieuawels/tpm-app:latest
