name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: self-hosted  # ton runner Windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # si ton Dockerfile s'appelle autrement ou est placé ailleurs, adapte ce chemin
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
