name: 🐳 Build & Deploy via Local Runner

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v4

    - name: 🧼 Déconnexion Docker précédente (sécurisée PowerShell)
      shell: powershell
      run: |
        try {
          docker logout
        } catch {
          Write-Host "⚠️ Docker était déjà déconnecté ou erreur ignorée"
        }

    - name: 🔐 Connexion sécurisée à Docker Hub
      shell: powershell
      run: |
        docker logout
        $pass = '${{ secrets.DOCKER_PASSWORD }}'
        $user = '${{ secrets.DOCKER_USERNAME }}'
        $pass | docker login -u $user --password-stdin


    - name: 🧪 Vérification accès à node:16-alpine
      run: docker pull node:16-alpine

    - name: 🐳 Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest .

    - name: 📤 Push image vers Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest

    - name: 🚀 Déploiement local
      run: |
        docker stop tpm-app-container || true
        docker rm tpm-app-container || true
        docker run -d --name tpm-app-container -p 8080:5000 ${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
