name: 🐳 Build & Deploy via Local Runner

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 📥 Cloner le dépôt
      uses: actions/checkout@v3

    - name: 🧼 Déconnexion Docker précédente
      shell: powershell
      run: |
        docker logout || Write-Host "Déjà déconnecté"

    - name: 🔐 Connexion à Docker Hub
      shell: powershell
      run: |
        $pass = "${{ secrets.DOCKER_PASSWORD }}"
        echo $pass | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 🧪 Test accès à node:16-alpine
      run: docker pull node:16-alpine

    - name: 🐳 Build Docker image
      run: docker build -t tpm-app .

    - name: 📤 Push image vers Docker Hub
      run: |
        docker tag tpm-app docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/tpm-app:latest

    - name: 🚀 Déploiement local
      run: |
        docker stop tpm-app-container || true
        docker rm tpm-app-container || true
        docker run -d --name tpm-app-container -p 8080:5000 mathieuawels/tpm-app:latest
