name: Build and Push Docker
on: [push]

jobs:
  build-and-push:
    runs-on: [self-hosted, Windows]  
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Disable Docker Desktop credStore
        if: ${{ runner.os == 'Windows' }}
        run: |
          $conf = "$Env:USERPROFILE\.docker\config.json"
          if (Test-Path $conf) {
            (Get-Content $conf) -notmatch '\"credsStore\"' | Set-Content $conf
          }
        shell: pwsh

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/mon-username/tpm-app:latest
